import copy

_TAG_MAPPING_KEYS = [
  "Buddh",
  "Christn",
  "MA",
  "Shinto",
  "X",
  "abbr",
  "adj",
  "adj-f",
  "adj-i",
  "adj-ix",
  "adj-kari",
  "adj-ku",
  "adj-na",
  "adj-nari",
  "adj-no",
  "adj-pn",
  "adj-shiku",
  "adj-t",
  "adv",
  "adv-n",
  "adv-to",
  "agric",
  "anat",
  "aphorism",
  "arch",
  "archeol",
  "archit",
  "art",
  "astron",
  "ateji",
  "audvid",
  "aux",
  "aux-adj",
  "aux-v",
  "aviat",
  "baseb",
  "biochem",
  "biol",
  "bot",
  "boxing",
  "bra",
  "bus",
  "cards",
  "char",
  "chem",
  "chmyth",
  "chn",
  "civeng",
  "cloth",
  "col",
  "comp",
  "company",
  "conj",
  "cop",
  "creat",
  "cryst",
  "ctr",
  "dated",
  "dei",
  "dent",
  "derog",
  "doc",
  "eK",
  "ecol",
  "econ",
  "ek",
  "elec",
  "electr",
  "embryo",
  "engr",
  "ent",
  "euph",
  "ev",
  "exp",
  "fam",
  "fem",
  "fict",
  "figskt",
  "film",
  "finc",
  "fish",
  "food",
  "form",
  "gai1",
  "gai2",
  "gardn",
  "genet",
  "geogr",
  "geol",
  "geom",
  "gikun",
  "given",
  "go",
  "golf",
  "gramm",
  "grmyth",
  "group",
  "hanaf",
  "hist",
  "hob",
  "hon",
  "horse",
  "hum",
  "iK",
  "ichi1",
  "ichi2",
  "id",
  "ik",
  "int",
  "internet",
  "io",
  "iv",
  "joc",
  "jpmyth",
  "kabuki",
  "ksb",
  "ktb",
  "kyb",
  "kyu",
  "law",
  "leg",
  "ling",
  "logic",
  "m-sl",
  "mahj",
  "male",
  "male-sl",
  "manga",
  "math",
  "mech",
  "med",
  "met",
  "mil",
  "min",
  "mining",
  "motor",
  "music",
  "myth",
  "n",
  "n-adv",
  "n-pr",
  "n-pref",
  "n-suf",
  "n-t",
  "nab",
  "net-sl",
  "news1",
  "news2",
  "nf01",
  "nf02",
  "nf03",
  "nf04",
  "nf05",
  "nf06",
  "nf07",
  "nf08",
  "nf09",
  "nf1",
  "nf10",
  "nf11",
  "nf12",
  "nf13",
  "nf14",
  "nf15",
  "nf16",
  "nf17",
  "nf18",
  "nf19",
  "nf2",
  "nf20",
  "nf21",
  "nf22",
  "nf23",
  "nf24",
  "nf25",
  "nf26",
  "nf27",
  "nf28",
  "nf29",
  "nf3",
  "nf30",
  "nf31",
  "nf32",
  "nf33",
  "nf34",
  "nf35",
  "nf36",
  "nf37",
  "nf38",
  "nf39",
  "nf4",
  "nf40",
  "nf41",
  "nf42",
  "nf43",
  "nf44",
  "nf45",
  "nf46",
  "nf47",
  "nf48",
  "nf5",
  "nf6",
  "nf7",
  "nf8",
  "nf9",
  "ng",
  "noh",
  "num",
  "oK",
  "obj",
  "obs",
  "obsc",
  "ok",
  "on-mim",
  "organization",
  "ornith",
  "osb",
  "oth",
  "paleo",
  "pathol",
  "person",
  "pharm",
  "phil",
  "photo",
  "physics",
  "physiol",
  "place",
  "pn",
  "poet",
  "pol",
  "politics",
  "pref",
  "print",
  "product",
  "proverb",
  "prowres",
  "prt",
  "psy",
  "psyanal",
  "psych",
  "quote",
  "rK",
  "rail",
  "rare",
  "relig",
  "rk",
  "rkb",
  "rommyth",
  "sK",
  "sens",
  "serv",
  "ship",
  "shogi",
  "sk",
  "ski",
  "sl",
  "spec1",
  "spec2",
  "sports",
  "stat",
  "station",
  "std",
  "stockm",
  "suf",
  "sumo",
  "surg",
  "surname",
  "telec",
  "thb",
  "tradem",
  "tsb",
  "tsug",
  "tv",
  "uK",
  "uk",
  "unc",
  "unclass",
  "v-unspec",
  "v1",
  "v1-s",
  "v2a-s",
  "v2b-k",
  "v2b-s",
  "v2d-k",
  "v2d-s",
  "v2g-k",
  "v2g-s",
  "v2h-k",
  "v2h-s",
  "v2k-k",
  "v2k-s",
  "v2m-k",
  "v2m-s",
  "v2n-s",
  "v2r-k",
  "v2r-s",
  "v2s-s",
  "v2t-k",
  "v2t-s",
  "v2w-s",
  "v2y-k",
  "v2y-s",
  "v2z-s",
  "v4b",
  "v4g",
  "v4h",
  "v4k",
  "v4m",
  "v4n",
  "v4r",
  "v4s",
  "v4t",
  "v5",
  "v5aru",
  "v5b",
  "v5g",
  "v5k",
  "v5k-s",
  "v5m",
  "v5n",
  "v5r",
  "v5r-i",
  "v5s",
  "v5t",
  "v5u",
  "v5u-s",
  "v5uru",
  "vet",
  "vi",
  "vidg",
  "vk",
  "vn",
  "vr",
  "vs",
  "vs-c",
  "vs-i",
  "vs-s",
  "vt",
  "vulg",
  "vz",
  "work",
  "yoji",
  "zool"
]

TAG_MAPPING_DEFAULT = {key: f"JMDict::{key}" for key in _TAG_MAPPING_KEYS}

DEFAULT_SOURCE_FIELDS = [
    {"name": "Vocab", "label": "Vocab", "enabled": True},
    {"name": "VocabReading", "label": "Vocab Reading", "enabled": True},
    {"name": "VocabKanji", "label": "Vocab Kanji", "enabled": True},
    {"name": "VocabAudio", "label": "Vocab Audio", "enabled": True},
    {"name": "PartOfSpeech", "label": "Part of Speech", "enabled": True},
    {"name": "GlossaryJMDictGerHTML", "label": "Glossary JMDict DE (HTML)", "enabled": True},
    {"name": "GlossaryJitendexEngHTML", "label": "Glossary Jitendex EN (HTML)", "enabled": True},
    {"name": "GlossaryFirst", "label": "Glossary First", "enabled": True},
    {"name": "SelectionText", "label": "Selection Text", "enabled": True},
    {"name": "Tags", "label": "Tags", "enabled": True},
    {"name": "FreqJPDB", "label": "Freq JPDB", "enabled": True},
    {"name": "FeqJPDB", "label": "Freq JPDB (legacy)", "enabled": True},
    {"name": "FreqJLPT", "label": "Freq JLPT", "enabled": True},
    {"name": "FreqHarmonic", "label": "Freq Harmonic", "enabled": False},
    {"name": "SourceTitle", "label": "Source Title", "enabled": False},
    {"name": "SourceUrl", "label": "Source URL", "enabled": False},
    {"name": "LinkedNotes", "label": "Linked Notes", "enabled": False},
]

DEFAULT_VIRTUAL_FIELDS = [
    {
        "id": "VocabMeaning",
        "name": "Vocab Meaning (SelectionText -> GlossaryFirst)",
        "type": "fallback",
        "primary": "SelectionText",
        "fallback": "GlossaryFirst",
    },
    {"id": "VocabHepburn", "name": "Vocab Hepburn", "type": "to_hepburn", "source": "VocabReading"},
    {"id": "FamilyID", "name": "Family ID", "type": "copy", "source": "Vocab"},
    {"id": "LinkedCards", "name": "Source Note Link", "type": "note_link", "label": "Source"},
]

DEFAULT_CATEGORIES = [
    {
        "id": "verb",
        "name": "Verbs",
        "note_type_id": None,
        "filter": {"source_field": "PartOfSpeech", "values": ["godan", "ichidan", "suru"]},
        "field_map": {},
    },
    {
        "id": "adjective",
        "name": "Adjectives",
        "note_type_id": None,
        "filter": {"source_field": "PartOfSpeech", "values": ["na", "i", "no"]},
        "field_map": {},
    },
    {
        "id": "other",
        "name": "Other",
        "note_type_id": None,
        "filter": {"source_field": "PartOfSpeech", "values": []},
        "field_map": {},
    },
]

DEFAULT_CONFIG = {
    "enabled": True,
    "run_on_sync": True,
    "run_on_card_added": False,
    "source_note_type_id": None,
    "source_fields": DEFAULT_SOURCE_FIELDS,
    "virtual_fields": DEFAULT_VIRTUAL_FIELDS,
    "categories": DEFAULT_CATEGORIES,
    "hepburn": {"engine": "pykakasi", "fallback": "simple"},
    "tags": {
        "processed_tag": "_intern::yomitan::processed",
        "export_tag": "_intern::yomitan_export",
        "link_tag_prefix": "_intern::yomitan",
    },
    "debug": {
        "enabled": False,
        "path": "ajpc-yomitran.log",
    },
    "tag_transform": {
        "prefix": "",
        "mapping": TAG_MAPPING_DEFAULT,
        "drop": [
            "spec1",
            "spec2",
            "news1",
            "news2",
            "\u2b50",
            "\u2605",
            "\u2606",
            "\U0001f31f",
        ],
    },
}


def merge_config(default: dict, custom: dict) -> dict:
    if custom is None:
        return copy.deepcopy(default)
    merged = copy.deepcopy(default)
    for key, value in custom.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = merge_config(merged[key], value)
        else:
            merged[key] = value
    return merged
